#!/usr/bin/env python

import sys
import re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print("commit-msg: On branch '%s'" % branch)

if branch.startswith('issue-'):
    print("commit-msg: Oh yeah, it's an issue branch.")
    result = re.match('issue-(.*)', branch)
    issue_number = result.group(1)
    required_message = 'ISSUE-%s' % issue_number

    with open(commit_msg_filepath, 'r') as f:
        content = f.read()
        if not content.startswith(required_message):
            print("commit-msg: Error! The commit message must start with '%s'" % required_message)
            sys.exit(1)
